
version: 2
# If you have jobs to do so start
jobs:
    #if you have only one job then add build
    build:
        docker:
          - image: circleci/python:3.7
        
        working_directory: ~/repo

        steps:
        # Step1: obtain repo from github
        - checkout
        # Step2: create virtual env and install dependencies
        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
        # Step3: run linter and tests
        - run:
            name: run tests
            command: |
              . venv/bin/activate
              flake8 --exclude=venv* --statistic
              pytest -v --cov=calculator






